"""Axiom One - Agent Plane

Structured AI agent system with safety controls, bounded scope, and audit trails.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum, auto

UTC = UTC
from typing import Any, Optional

from axiom_one_graph import (
    AxiomGraph,
    DomainType,
    NodeType,
    generate_node_id,
)


class AgentRole(Enum):
    """Specialized agent roles."""

    REPO_DEBUGGER = "repo_debugger"
    CODE_GENERATOR = "code_generator"
    REFACTOR = "refactor"
    PACKAGING = "packaging"
    TEST = "test"
    MIGRATION = "migration"
    INFRA = "infra"
    OBSERVABILITY = "observability"
    INCIDENT = "incident"
    SECURITY = "security"
    COMPLIANCE = "compliance"
    ARCHITECTURE = "architecture"
    DOCS = "docs"
    RELEASE = "release"


class ActionType(Enum):
    """Agent action types."""

    READ_FILE = auto()
    WRITE_FILE = auto()
    RUN_COMMAND = auto()
    RUN_TEST = auto()
    SEARCH_CODE = auto()
    CREATE_PR = auto()
    APPLY_PATCH = auto()


@dataclass
class AgentTool:
    """A tool available to an agent."""

    name: str
    description: str
    action_type: ActionType
    requires_approval: bool
    blast_radius: str  # local, repo, system


@dataclass
class AgentAction:
    """A single action taken by an agent."""

    id: str
    agent_id: str
    action_type: ActionType
    params: dict[str, Any]
    status: str  # pending, running, success, failed
    started_at: str
    completed_at: str = None
    result: dict[str, Any] = None
    evidence: dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentPlan:
    """A plan generated by the agent."""

    id: str
    agent_id: str
    goal: str
    steps: list[dict[str, Any]]
    estimated_blast_radius: str
    requires_approval: bool
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


@dataclass
class Agent:
    """An AI agent in the Agent Plane."""

    id: str
    name: str
    role: AgentRole
    scope: list[str]  # Allowed paths/modules
    tools: list[AgentTool]
    permissions: list[str]
    budget_limit: float  # Max cost per run
    approval_threshold: str  # auto, low, medium, high
    memory: list[dict[str, Any]] = field(default_factory=list)
    action_log: list[AgentAction] = field(default_factory=list)
    status: str = "inactive"

    def __post_init__(self):
        if not self.id:
            self.id = generate_node_id(DomainType.AI, NodeType.AGENT, self.name)


@dataclass
class AgentSafetyPolicy:
    """Safety policy for agent execution."""

    dry_run_first: bool = True
    require_approval_for_writes: bool = True
    max_actions_per_run: int = 50
    max_budget_usd: float = 10.0
    allowed_file_patterns: list[str] = field(default_factory=lambda: ["*.py", "*.md", "*.toml"])
    blocked_commands: list[str] = field(default_factory=lambda: ["rm -rf /", "sudo", "chmod"])


class AgentPlane:
    """
    The Agent Plane - structured AI execution system.

    Features:
    - 15 specialized agent roles
    - Bounded tool access per agent
    - Safety policies with approval workflows
    - Evidence logging for audit
    - Budget tracking
    """

    def __init__(self, graph: AxiomGraph, policy: Optional[AgentSafetyPolicy] = None):
        self.graph = graph
        self.policy = policy or AgentSafetyPolicy()
        self.agents: dict[str, Agent] = {}
        self._setup_default_agents()

    def _setup_default_agents(self) -> None:
        """Create default agents for each role."""
        repo_debugger_tools = [
            AgentTool("read_file", "Read file contents", ActionType.READ_FILE, False, "local"),
            AgentTool("run_command", "Run shell command", ActionType.RUN_COMMAND, True, "repo"),
            AgentTool("run_test", "Run tests", ActionType.RUN_TEST, False, "repo"),
            AgentTool("search_code", "Search codebase", ActionType.SEARCH_CODE, False, "repo"),
            AgentTool("apply_patch", "Apply code patch", ActionType.APPLY_PATCH, True, "repo"),
            AgentTool("create_pr", "Create pull request", ActionType.CREATE_PR, True, "repo"),
        ]

        self.agents["repo-debugger"] = Agent(
            id="",
            name="Repo Debugger",
            role=AgentRole.REPO_DEBUGGER,
            scope=["/repo"],
            tools=repo_debugger_tools,
            permissions=["read:code", "write:code", "run:test"],
            budget_limit=5.0,
            approval_threshold="medium",
        )

        code_gen_tools = [
            AgentTool("read_file", "Read file", ActionType.READ_FILE, False, "local"),
            AgentTool("write_file", "Write file", ActionType.WRITE_FILE, True, "repo"),
            AgentTool("search_code", "Search code", ActionType.SEARCH_CODE, False, "repo"),
        ]

        self.agents["code-generator"] = Agent(
            id="",
            name="Code Generator",
            role=AgentRole.CODE_GENERATOR,
            scope=["/repo/src"],
            tools=code_gen_tools,
            permissions=["read:code", "write:code"],
            budget_limit=3.0,
            approval_threshold="high",
        )

    async def execute_agent(
        self,
        agent_id: str,
        goal: str,
        context: dict[str, Any],
        dry_run: bool = True,
    ) -> dict[str, Any]:
        """Execute an agent with full safety controls."""
        agent = self.agents.get(agent_id)
        if not agent:
            return {"error": f"Agent {agent_id} not found"}

        agent.status = "running"

        # Create plan
        plan = await self._create_plan(agent, goal, context)

        # Check if approval required
        if plan.requires_approval or self.policy.dry_run_first:
            return {
                "status": "awaiting_approval",
                "plan": plan,
                "agent_id": agent_id,
                "message": "Plan requires approval before execution",
            }

        # Execute plan
        results = []
        for step in plan.steps:
            if len(agent.action_log) >= self.policy.max_actions_per_run:
                break

            action = await self._execute_step(agent, step, dry_run)
            results.append(action)
            agent.action_log.append(action)

            if action.status == "failed":
                break

        agent.status = "completed"

        return {
            "status": "completed",
            "agent_id": agent_id,
            "plan_id": plan.id,
            "steps_executed": len(results),
            "results": results,
        }

    async def _create_plan(self, agent: Agent, goal: str, context: dict[str, Any]) -> AgentPlan:
        """Generate execution plan for goal."""
        # Simplified plan generation
        steps = [
            {"action": "analyze", "description": f"Analyze goal: {goal}"},
            {"action": "plan", "description": "Generate execution steps"},
            {"action": "execute", "description": "Execute with safety controls"},
            {"action": "verify", "description": "Verify results"},
        ]

        return AgentPlan(
            id=generate_node_id(DomainType.AI, NodeType.AGENT, f"plan:{agent.name}"),
            agent_id=agent.id,
            goal=goal,
            steps=steps,
            estimated_blast_radius="repo",
            requires_approval=agent.approval_threshold in ["medium", "high"],
        )

    async def _execute_step(self, agent: Agent, step: dict[str, Any], dry_run: bool) -> AgentAction:
        """Execute a single plan step."""
        action = AgentAction(
            id=generate_node_id(DomainType.AI, NodeType.AGENT, f"action:{agent.name}"),
            agent_id=agent.id,
            action_type=ActionType.READ_FILE,  # Default
            params=step,
            status="running",
            started_at=datetime.now(UTC).isoformat(),
        )

        if dry_run:
            action.status = "success"
            action.result = {"dry_run": True, "message": "Would execute: " + str(step)}
        else:
            # Actual execution would happen here
            action.status = "success"
            action.result = {"executed": True}

        action.completed_at = datetime.now(UTC).isoformat()
        return action

    def get_agent(self, agent_id: str) -> Optional[Agent]:
        return self.agents.get(agent_id)

    def list_agents(self) -> list[Agent]:
        return list(self.agents.values())
