#!/usr/bin/env python3

"""Use AMOS Brain with the offline coding LLM."""

import asyncio
import sys

sys.path.insert(0, ".")

from backend.llm_providers import LLMRequest, Message, llm_router


async def generate_code():
    print("=" * 60)
    print("AMOS Brain + Qwen 2.5 Coder 14B (Offline)")
    print("=" * 60)
    print("\nTask: Create a Python class for a thread-safe LRU cache")
    print("Thinking...\n")

    request = LLMRequest(
        messages=[
            Message(
                role="system",
                content="You are an expert Python developer. "
                "Write clean, well-documented code with type hints.",
            ),
            Message(
                role="user",
                content="Create a Python class for a thread-safe LRU cache "
                "with get, put, and delete methods. "
                "Include type hints and docstrings.",
            ),
        ],
        model="qwen2.5-coder:14b",
        temperature=0.3,
    )

    response = await llm_router.route_request(request, preference="ollama")

    print(f"Generated by: {response.model}")
    print(f"Provider: {response.provider}")
    print(f"Latency: {response.latency_ms:.0f}ms")
    print(f"Tokens used: {response.usage}")
    print("\n" + "=" * 60)
    print("GENERATED CODE:")
    print("=" * 60)
    print(response.content)
    print("=" * 60)

    await llm_router.close_all()


async def solve_problem():
    """Solve a coding interview problem."""
    print("\n" + "=" * 60)
    print("Problem: Merge k sorted linked lists")
    print("=" * 60)
    print("Solving...\n")

    request = LLMRequest(
        messages=[
            Message(
                role="system",
                content="You are an expert algorithmist. Write efficient, well-tested code.",
            ),
            Message(
                role="user",
                content="Given an array of k linked-lists, each sorted in "
                "ascending order, merge them into one sorted linked-list. "
                "Optimize for time complexity.",
            ),
        ],
        model="qwen2.5-coder:14b",
        temperature=0.2,
    )

    response = await llm_router.route_request(request, preference="ollama")

    print(f"Response from: {response.model}")
    print(f"Time: {response.latency_ms:.0f}ms")
    print("\n" + "=" * 60)
    print(response.content)
    print("=" * 60)

    await llm_router.close_all()


async def main():
    """Run brain coding tasks."""
    await generate_code()
    await solve_problem()


if __name__ == "__main__":
    asyncio.run(main())
