"""TaskExecutor Agent - Generated by AMOS FACTORY
Purpose: Execute shell commands safely
Capabilities: run_command, check_status, log_output
"""

import logging
import subprocess
from dataclasses import dataclass
from datetime import datetime


@dataclass
class TaskResult:
    """Result of task execution."""

    success: bool
    stdout: str
    stderr: str
    exit_code: int
    command: str
    executed_at: str


class TaskExecutor:
    """AMOS Task Execution Agent.

    Safely executes shell commands with logging and validation.
    """

    # Safe commands only
    ALLOWED_COMMANDS = [
        "ls",
        "cat",
        "echo",
        "pwd",
        "whoami",
        "python",
        "python3",
        "pip",
        "curl",
        "grep",
        "head",
        "tail",
        "wc",
        "find",
        "du",
    ]

    # Destructive commands blocked
    BLOCKED_PATTERNS = ["rm -rf", "rm -f /", "mkfs", "dd if", "> /dev", ":(){", "chmod 777 /"]

    def __init__(self):
        self.history: list[TaskResult] = []
        self.setup_logging()

    def setup_logging(self):
        """Configure execution logging."""
        logging.basicConfig(
            level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        self.logger = logging.getLogger("TaskExecutor")

    def validate_command(self, command: str) -> tuple[bool, str]:
        """Check if command is safe to execute."""
        # Check blocked patterns
        for pattern in self.BLOCKED_PATTERNS:
            if pattern in command.lower():
                return False, f"Blocked destructive pattern: {pattern}"

        # Check if base command is allowed
        base_cmd = command.split()[0] if command else ""
        if base_cmd not in self.ALLOWED_COMMANDS:
            return False, f"Command not in allowed list: {base_cmd}"

        return True, "OK"

    def run_command(self, command: str, timeout: int = 30) -> TaskResult:
        """Execute a shell command safely."""
        # Validate
        is_safe, reason = self.validate_command(command)
        if not is_safe:
            self.logger.error(f"Command blocked: {reason}")
            return TaskResult(
                success=False,
                stdout="",
                stderr=f"BLOCKED: {reason}",
                exit_code=-1,
                command=command,
                executed_at=datetime.utcnow().isoformat(),
            )

        # Execute
        self.logger.info(f"Executing: {command}")
        try:
            result = subprocess.run(
                command, shell=True, capture_output=True, text=True, timeout=timeout
            )

            task_result = TaskResult(
                success=result.returncode == 0,
                stdout=result.stdout,
                stderr=result.stderr,
                exit_code=result.returncode,
                command=command,
                executed_at=datetime.utcnow().isoformat(),
            )

            self.history.append(task_result)
            self.logger.info(f"Completed: exit_code={result.returncode}")
            return task_result

        except subprocess.TimeoutExpired:
            self.logger.error(f"Timeout after {timeout}s")
            return TaskResult(
                success=False,
                stdout="",
                stderr=f"Timeout after {timeout} seconds",
                exit_code=-1,
                command=command,
                executed_at=datetime.utcnow().isoformat(),
            )
        except Exception as e:
            self.logger.error(f"Error: {e}")
            return TaskResult(
                success=False,
                stdout="",
                stderr=str(e),
                exit_code=-1,
                command=command,
                executed_at=datetime.utcnow().isoformat(),
            )

    def check_status(self) -> dict:
        """Get agent status."""
        return {
            "agent": "TaskExecutor",
            "total_executions": len(self.history),
            "successful": sum(1 for r in self.history if r.success),
            "failed": sum(1 for r in self.history if not r.success),
            "last_command": self.history[-1].command if self.history else None,
        }

    def get_history(self, limit: int = 10) -> list[TaskResult]:
        """Get execution history."""
        return self.history[-limit:]


# Factory function for AMOS integration
def create_agent() -> TaskExecutor:
    """Create a new TaskExecutor agent instance."""
    return TaskExecutor()


if __name__ == "__main__":
    # Demo usage
    agent = create_agent()

    print("TaskExecutor Agent Demo")
    print("=" * 40)

    # Test safe command
    result = agent.run_command("echo 'Hello from AMOS Agent'")
    print(f"Command: {result.command}")
    print(f"Success: {result.success}")
    print(f"Output: {result.stdout.strip()}")

    # Test blocked command
    result = agent.run_command("rm -rf /")
    print("\nBlocked command test:")
    print("Command: rm -rf /")
    print(f"Blocked: {not result.success}")
    print(f"Reason: {result.stderr}")

    # Status
    print("\nAgent Status:")
    print(agent.check_status())
