"""IP Tracker — Intellectual property management

Tracks IP assets, licenses, and protects intellectual
property generated by AMOS.
"""

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional


class IPType(Enum):
    """Types of intellectual property."""

    COPYRIGHT = "copyright"
    PATENT = "patent"
    TRADEMARK = "trademark"
    TRADE_SECRET = "trade_secret"
    LICENSE = "license"
    OPEN_SOURCE = "open_source"


class IPStatus(Enum):
    """Status of IP asset."""

    DRAFT = "draft"
    PENDING = "pending"
    REGISTERED = "registered"
    PROTECTED = "protected"
    EXPIRED = "expired"
    ABANDONED = "abandoned"


@dataclass
class IPAsset:
    """An intellectual property asset."""

    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    title: str = ""
    ip_type: IPType = IPType.COPYRIGHT
    status: IPStatus = IPStatus.DRAFT
    description: str = ""
    creator: str = ""
    owner: str = ""
    created_date: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    registration_date: str = None
    registration_number: str = None
    expiry_date: str = None
    license_type: str = ""  # MIT, GPL, Apache, Proprietary, etc.
    related_files: List[str] = field(default_factory=list)
    tags: List[str] = field(default_factory=list)
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            **asdict(self),
            "ip_type": self.ip_type.value,
            "status": self.status.value,
        }


@dataclass
class IPLicense:
    """A license for IP usage."""

    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    asset_id: str = ""
    licensee: str = ""
    license_type: str = ""  # exclusive, non-exclusive, etc.
    terms: str = ""
    start_date: str = ""
    end_date: str = None
    royalty_rate: float = 0.0
    active: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class IPTracker:
    """Manages intellectual property assets.

    Tracks IP creation, licenses, and ensures proper
    protection and attribution.
    """

    def __init__(self, data_dir: Optional[Path] = None):
        if data_dir is None:
            data_dir = Path(__file__).parent / "data"
        self.data_dir = data_dir
        self.data_dir.mkdir(parents=True, exist_ok=True)

        self.assets: List[IPAsset] = []
        self.licenses: List[IPLicense] = []

        self._load_data()

    def _load_data(self):
        """Load IP data from disk."""
        data_file = self.data_dir / "ip_assets.json"
        if data_file.exists():
            try:
                data = json.loads(data_file.read_text())
                for a_data in data.get("assets", []):
                    asset = IPAsset(
                        id=a_data["id"],
                        title=a_data["title"],
                        ip_type=IPType(a_data["ip_type"]),
                        status=IPStatus(a_data["status"]),
                        description=a_data.get("description", ""),
                        creator=a_data.get("creator", ""),
                        owner=a_data.get("owner", ""),
                        created_date=a_data["created_date"],
                        registration_date=a_data.get("registration_date"),
                        registration_number=a_data.get("registration_number"),
                        expiry_date=a_data.get("expiry_date"),
                        license_type=a_data.get("license_type", ""),
                        related_files=a_data.get("related_files", []),
                        tags=a_data.get("tags", []),
                        notes=a_data.get("notes", ""),
                    )
                    self.assets.append(asset)

                for l_data in data.get("licenses", []):
                    license = IPLicense(**l_data)
                    self.licenses.append(license)
            except Exception as e:
                print(f"[IP] Error loading data: {e}")

    def save(self):
        """Save IP data to disk."""
        data_file = self.data_dir / "ip_assets.json"
        data = {
            "saved_at": datetime.now(UTC).isoformat(),
            "assets": [a.to_dict() for a in self.assets],
            "licenses": [l.to_dict() for l in self.licenses],
        }
        data_file.write_text(json.dumps(data, indent=2))

    def register_asset(
        self,
        title: str,
        ip_type: IPType,
        creator: str,
        description: str = "",
        license_type: str = "",
    ) -> IPAsset:
        """Register a new IP asset."""
        asset = IPAsset(
            title=title,
            ip_type=ip_type,
            creator=creator,
            owner=creator,
            description=description,
            license_type=license_type,
        )
        self.assets.append(asset)
        self.save()
        return asset

    def get_asset(self, asset_id: str) -> Optional[IPAsset]:
        """Get an IP asset by ID."""
        for asset in self.assets:
            if asset.id == asset_id:
                return asset
        return None

    def update_status(self, asset_id: str, status: IPStatus) -> bool:
        """Update IP asset status."""
        asset = self.get_asset(asset_id)
        if asset:
            asset.status = status
            if status == IPStatus.REGISTERED:
                asset.registration_date = datetime.now(UTC).isoformat()
            self.save()
            return True
        return False

    def add_license(
        self,
        asset_id: str,
        licensee: str,
        license_type: str,
        terms: str = "",
    ) -> Optional[IPLicense]:
        """Add a license for an asset."""
        asset = self.get_asset(asset_id)
        if not asset:
            return None

        license = IPLicense(
            asset_id=asset_id,
            licensee=licensee,
            license_type=license_type,
            terms=terms,
            start_date=datetime.now(UTC).isoformat(),
        )
        self.licenses.append(license)
        self.save()
        return license

    def check_infringement_risk(self, content: str) -> Dict[str, Any]:
        """Check content for potential IP infringement."""
        risks = []
        confidence = "low"

        # Check for known trademarks
        trademarks = [a for a in self.assets if a.ip_type == IPType.TRADEMARK]
        for tm in trademarks:
            if tm.title.lower() in content.lower():
                risks.append(f"Contains trademark: {tm.title}")

        # Check for proprietary indicators
        proprietary_terms = ["proprietary", "confidential", "trade secret"]
        for term in proprietary_terms:
            if term in content.lower():
                risks.append(f"Contains proprietary indicator: {term}")
                confidence = "medium"

        return {
            "risks": risks,
            "risk_count": len(risks),
            "confidence": confidence,
            "safe_to_use": len(risks) == 0,
        }

    def get_portfolio_summary(self) -> Dict[str, Any]:
        """Get IP portfolio summary."""
        by_type = {}
        by_status = {}

        for asset in self.assets:
            t = asset.ip_type.value
            s = asset.status.value
            by_type[t] = by_type.get(t, 0) + 1
            by_status[s] = by_status.get(s, 0) + 1

        active_licenses = len([l for l in self.licenses if l.active])

        return {
            "total_assets": len(self.assets),
            "by_type": by_type,
            "by_status": by_status,
            "registered": len([a for a in self.assets if a.status == IPStatus.REGISTERED]),
            "active_licenses": active_licenses,
            "recently_created": len(
                [
                    a
                    for a in self.assets
                    if (datetime.now(UTC) - datetime.fromisoformat(a.created_date)).days <= 30
                ]
            ),
        }

    def get_open_source_recommendation(self, asset_id: str) -> str:
        """Recommend open source license for an asset."""
        asset = self.get_asset(asset_id)
        if not asset:
            return "Asset not found"

        # Simple recommendations based on asset type
        if asset.ip_type == IPType.COPYRIGHT:
            if "software" in asset.description.lower() or "code" in asset.description.lower():
                return "MIT (permissive) or GPL (copyleft) recommended"
            else:
                return "CC-BY or CC-BY-SA recommended"
        elif asset.ip_type == IPType.PATENT:
            return "Consider patent + open source implementation license"
        else:
            return "Standard protection recommended"


# Global instance
_TRACKER: Optional[IPTracker] = None


def get_ip_tracker(data_dir: Optional[Path] = None) -> IPTracker:
    """Get or create global IP tracker."""
    global _TRACKER
    if _TRACKER is None:
        _TRACKER = IPTracker(data_dir)
    return _TRACKER


if __name__ == "__main__":
    print("IP Tracker (11_LEGAL_BRAIN)")
    print("=" * 40)

    tracker = get_ip_tracker()

    # Register sample asset
    asset = tracker.register_asset(
        title="AMOS Cognitive Engine",
        ip_type=IPType.COPYRIGHT,
        creator="Trang",
        description="Core cognitive runtime architecture",
        license_type="Proprietary",
    )
    print(f"\nRegistered asset: {asset.title}")

    print(f"\nRecommendation: {tracker.get_open_source_recommendation(asset.id)}")

    print("\nPortfolio Summary:")
    summary = tracker.get_portfolio_summary()
    print(f"  Total assets: {summary['total_assets']}")
    print(f"  By type: {summary['by_type']}")
