#!/usr/bin/env python3
"""AMOS Worker Engine (06_MUSCLE)
==============================

Executable worker implementations for the AMOS Organism.
Connects cognitive runtime to actual task execution.

Owner: Trang
Version: 1.0.0
"""

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional


@dataclass
class WorkerResult:
    success: bool
    output: str
    artifacts: list[Path]
    metadata: dict[str, Any]


class AmosWorkerEngine:
    """Muscle subsystem - executes tasks via workers.
    Integrates with cognitive runtime for intelligent execution.
    """

    def __init__(self, organism_root: Path) -> None:
        self.root = organism_root
        self.brain_root = organism_root.parent / "_AMOS_BRAIN"
        self.runtime = None
        self._init_cognitive_runtime()

    def _init_cognitive_runtime(self) -> None:
        """Initialize AMOS cognitive runtime if available."""
        try:
            from AMOS_ORGANISM_OS.BRAIN.amos_cognitive_runtime import AMOSCognitiveRuntime

            self.runtime = AMOSCognitiveRuntime(self.brain_root)
        except Exception as e:
            print(f"[WORKER] Cognitive runtime not available: {e}")
            self.runtime = None

    def execute_plan(self, plan: dict[str, Any], context: dict = None) -> WorkerResult:
        """Execute a plan generated by the planner."""
        steps = plan.get("steps", [])
        artifacts: list[Path] = []

        for i, step in enumerate(steps, 1):
            print(f"[WORKER] Executing step {i}/{len(steps)}: {step.get('action')}")

            result = self._execute_step(step, context)
            if not result["success"]:
                error_msg = result.get("error", "Unknown error")
                return WorkerResult(
                    success=False,
                    output=f"Step {i} failed: {error_msg}",
                    artifacts=artifacts,
                    metadata={"failed_step": i, "step_count": len(steps)},
                )

            artifacts.extend(result.get("artifacts", []))

        return WorkerResult(
            success=True,
            output=f"Executed {len(steps)} steps successfully",
            artifacts=artifacts,
            metadata={"step_count": len(steps)},
        )

    def _execute_step(self, step: dict[str, Any], context: dict) -> dict[str, Any]:
        """Execute a single step."""
        action = step.get("action")

        handlers: dict[str, Callable] = {
            "generate_code": self._handle_code_generation,
            "write_file": self._handle_write_file,
            "run_command": self._handle_run_command,
            "analyze": self._handle_analysis,
            "audit": self._handle_audit,
        }

        handler = handlers.get(action, self._handle_unknown)
        return handler(step, context)

    def _handle_code_generation(self, step: dict[str, Any], context: dict) -> dict[str, Any]:
        """Generate code using cognitive runtime."""
        if not self.runtime:
            return {"success": False, "error": "Cognitive runtime not available"}

        prompt = step.get("prompt", "")
        target_file = step.get("target_file")

        # Use cognitive runtime to generate
        result = self.runtime.think(
            f"Generate Python code for: {prompt}", "design_and_architecture"
        )

        synthesis = result.get("synthesis", {})
        chain = synthesis.get("reasoning_chain", ["# No code generated"])
        code = chain[-1]

        if target_file:
            path = self.root / target_file
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(code, encoding="utf-8")
            return {"success": True, "artifacts": [path]}

        return {"success": True, "output": code}

    def _handle_write_file(self, step: dict[str, Any], context: dict) -> dict[str, Any]:
        """Write content to file."""
        target = step.get("target_file")
        content = step.get("content", "")

        if not target:
            return {"success": False, "error": "No target file specified"}

        path = self.root / target
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

        return {"success": True, "artifacts": [path]}

    def _handle_run_command(self, step: dict[str, Any], context: dict) -> dict[str, Any]:
        """Execute shell command."""
        command = step.get("command", [])
        if not command:
            return {"success": False, "error": "No command specified"}

        try:
            result = subprocess.run(
                command, capture_output=True, text=True, timeout=30, cwd=self.root
            )
            return {
                "success": result.returncode == 0,
                "output": result.stdout,
                "error": result.stderr if result.returncode != 0 else None,
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def _handle_analysis(self, step: dict[str, Any], context: dict) -> dict[str, Any]:
        """Perform analysis using cognitive runtime."""
        if not self.runtime:
            return {"success": False, "error": "Runtime not available"}

        topic = step.get("topic", "")
        result = self.runtime.think(topic, "diagnostic_analysis")

        return {"success": True, "output": json.dumps(result, indent=2), "artifacts": []}

    def _handle_audit(self, step: dict[str, Any], context: dict) -> dict[str, Any]:
        """Audit a decision or output."""
        if not self.runtime:
            return {"success": False, "error": "Runtime not available"}

        target = step.get("target", "")
        result = self.runtime.think(target, "audit_and_critique")

        return {
            "success": True,
            "output": json.dumps(result.get("law_compliance", {}), indent=2),
            "artifacts": [],
        }

    def _handle_unknown(self, step: dict[str, Any], context: dict) -> dict[str, Any]:
        """Handle unknown actions."""
        return {"success": False, "error": f"Unknown action: {step.get('action')}"}


class CodeWorker:
    """Specialized code generation worker."""

    def __init__(self, engine: AmosWorkerEngine) -> None:
        self.engine = engine

    def generate(self, prompt: str, target_file: str = None) -> WorkerResult:
        """Generate code from prompt."""
        plan = {
            "steps": [{"action": "generate_code", "prompt": prompt, "target_file": target_file}]
        }
        return self.engine.execute_plan(plan)


class FileWorker:
    """File operations worker."""

    def __init__(self, engine: AmosWorkerEngine) -> None:
        self.engine = engine

    def write(self, content: str, target_file: str) -> WorkerResult:
        """Write content to file."""
        plan = {"steps": [{"action": "write_file", "content": content, "target_file": target_file}]}
        return self.engine.execute_plan(plan)


# Global worker instance
_WORKER_ENGINE: Optional[AmosWorkerEngine] = None


def get_worker_engine(organism_root: Optional[Path] = None) -> AmosWorkerEngine:
    """Get or create global worker engine instance."""
    global _WORKER_ENGINE
    if _WORKER_ENGINE is None:
        if organism_root is None:
            organism_root = Path(__file__).parent.parent
        _WORKER_ENGINE = AmosWorkerEngine(organism_root)
    return _WORKER_ENGINE


if __name__ == "__main__":
    print("AMOS Worker Engine (06_MUSCLE)")
    print("================================")

    engine = get_worker_engine()

    # Test code generation
    print("\n[TEST] Code generation...")
    code_worker = CodeWorker(engine)
    result = code_worker.generate(
        "Create a function that calculates factorial", "test_output/factorial.py"
    )

    print(f"Success: {result.success}")
    print(f"Artifacts: {result.artifacts}")
